GET http://127.0.0.1:8000/api/clients?filters[name]=Ан&filters[email]=PjBw5BNQXn@gmail.com
Accept: application/json
Authorization: Bearer :$1$Lb1FK6No$dsHLVYkyCT/0vejYgMVI90

###

GET http://127.0.0.1:8000/api/clients/11
Accept: application/json
Authorization: Bearer :$1$Lb1FK6No$dsHLVYkyCT/0vejYgMVI90

###

GET http://127.0.0.1:8000/api/clients/14
Accept: application/json
Authorization: Bearer :$1$Lb1FK6No$dsHLVYkyCT/0vejYgMVI90

###

DELETE http://127.0.0.1:8000/api/clients/14
Accept: application/json
Authorization: Bearer :$1$Lb1FK6No$dsHLVYkyCT/0vejYgMVI90

###

GET http://127.0.0.1:8000/api/error
Accept: application/json

###

POST http://127.0.0.1:8000/api/clients
Accept: application/json
Content-Type: application/json
Authorization: Bearer :$1$Lb1FK6No$dsHLVYkyCT/0vejYgMVI90

{
  "first_name": "Василий",
  "last_name": "Васильев"
}

###

PATCH http://127.0.0.1:8000/api/clients/13
Accept: application/json
Content-Type: application/json
Authorization: Bearer :$1$Yz7zY6V/$6q/Fn0UWCPl8M2xLii6tQ0

{
  "first_name": "Петр",
  "last_name": "Васильев"
}

###

GET http://127.0.0.1:8000/api/clients/13/phones
Accept: application/json

###

GET http://127.0.0.1:8000/api/clients/13/emails
Accept: application/json

###

POST http://127.0.0.1:8000/api/clients/13/phones
Accept: application/json
Content-Type: application/json

{
  "phone": 89158375199
}